POSE_MODEL = "mediapipe"
POSE_CONFIDENCE_THRESHOLD = 0.5
POSE_MODEL = "mediapipe"
POSE_CONFIDENCE_THRESHOLD = 0.5
VIDEO_DURATION_SECONDS = 15
VIDEO_FPS = 30
AUDIO_DURATION_SECONDS = 15
AUDIO_SAMPLE_RATE = 16000
AUDIO_N_MFCC = 13
MILESTONE_THRESHOLDS = {
'ON_TRACK': 0.75,
'MONITOR': (0.5, 0.75),
'RECOMMEND_EVALUATION': 0.5
}
